## code to prepare `FunderCodes` dataset goes here

# Section 2.06 in Data Dictionary
FunderCodes <- tibble::tribble(
  ~Code, ~Description,
  1L, "HUD: CoC - Homelessness Prevention (High Performing Comm. Only)",
  2L, "HUD: CoC - Permanent Supportive Housing",
  3L, "HUD: CoC - Rapid Re-Housing",
  4L, "HUD: CoC - Supportive Services Only",
  5L, "HUD: CoC - Transitional Housing",
  6L, "HUD: CoC - Safe Haven",
  7L, "HUD: CoC - Single Room Occupancy (SRO)",
  43L, "HUD: CoC - Youth Homeless Demonstration Program (YHDP)",
  44L, "HUD: CoC - Joint Component TH/RRH",
  8L, "HUD: ESG - Emergency Shelter (operating and/or essential services)",
  9L, "HUD: ESG - Homelessness Prevention",
  10L, "HUD: ESG - Rapid Re-Housing",
  11L, "HUD: ESG - Street Outreach",
  47L, "HUD: ESG-CV",
  53L, "HUD: ESG-RUSH",
  54L, "HUD: Unsheltered Special NOFO",
  55L, "HUD: Rural Special NOFO",
  35L, "HUD: Pay for Success",
  13L, "HUD: HOPWA - Hotel/Motel Vouchers",
  14L, "HUD: HOPWA - Housing Information",
  15L, "HUD: HOPWA - Permanent Housing (facility based or TBRA)",
  16L, "HUD: HOPWA - Permanent Housing Placement",
  17L, "HUD: HOPWA - Short-Term Rent, Mortgage, Utility assistance",
  18L, "HUD: HOPWA - Short-Term Supportive Facility",
  19L, "HUD: HOPWA - Transitional Housing (facility based or TBRA)",
  48L, "HUD: HOPWA-CV",
  36L, "HUD: Public and Indian Housing (PIH) Programs",
  20L, "HUD: HUD/VASH",
  52L, "HUD: PIH (Emergency Housing Voucher)",
  50L, "HUD: HOME",
  51L, "HUD: HOME (ARP)",
  21L, "HHS: PATH - Street Outreach & Supportive Services Only",
  22L, "HHS: RHY - Basic Center Program (prevention and shelter)",
  23L, "HHS: RHY - Maternity Group Home for Pregnant and Parenting Youth",
  24L, "HHS: RHY - Transitional Living Program",
  25L, "HHS: RHY - Street Outreach Project",
  26L, "HHS: RHY - Demonstration Project",
  27L, "VA: CRS Contract Residential Services",
  37L, "VA: Grant Per Diem - Bridge Housing",
  38L, "VA: Grant Per Diem - Low Demand",
  39L, "VA: Grant Per Diem - Hospital to Housing",
  40L, "VA: Grant Per Diem - Clinical Treatment",
  41L, "VA: Grant Per Diem - Service Intensive Transitional Housing",
  42L, "VA: Grant Per Diem - Transition in Place",
  45L, "VA: Grant Per Diem - Case Management/Housing Retention",
  30L, "VA: Community Contract Safe Haven Program",
  33L, "VA: Supportive Services for Veteran Families",
  34L, "N/A",
  46L, "Local or Other Funding Source"
)

usethis::use_data(FunderCodes, overwrite = TRUE)
