## code to prepare `LivingCodes` dataset goes here

LivingCodes <- tibble::tribble(
  ~Code, ~Description, ~Category, ~GeneralCategory,
  16L, "Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside)", "Homeless", "Temporary",
  1L, "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter", "Homeless", "Temporary",
  18L, "Safe Haven", "Homeless", "Temporary",
  15L, "Foster care home or foster care group home", "Institutional", "Temporary",
  6L, "Hospital or other residential non-psychiatric medical facility", "Institutional", "Temporary",
  7L, "Jail, prison or juvenile detention facility", "Institutional", "Temporary",
  25L, "Long-term care facility or nursing home", "Institutional", "Not enough data",
  4L, "Psychiatric hospital or other psychiatric facility", "Institutional", "Temporary",
  5L, "Substance abuse treatment facility or deto center", "Institutional", "Temporary",
  29L, "Residential project or halfway house with no homeless criteria", "Institutional", "Temporary",
  14L, "Hotel or motel paid for without emergency shelter voucher", "Temporary", "Temporary",
  2L, "Transitional housing for homeless persons (including homeless youth)", "Homeless", "Temporary",
  32L, "Host Home (non-crisis)", "Temporary", "Temporary",
  13L, "Staying or living with friends, temporary tenure (e.g. room apartment or house)", "Temporary", "Temporary",
  36L, "Staying or living in a friend's room, apartment or house", "Not enough data", "Not enough data",
  12L, "Staying or living with family, temporary tenure (e.g. room, apartment or house)", "Temporary", "Temporary",
  22L, "Staying or living with family, permanent tenure", "Permanent", "Permanent",
  35L, "Staying or living in a family member's room, apartment or house", "Not enough data", "Not enough data",
  23L, "Staying or living with friends, permanent tenure", "Permanent", "Permanent",
  26L, "Moved from one HOPWA funded project to HOPWA PH", "Permanent", "Permanent",
  27L, "Moved from one HOPWA funded project to HOPWA TH", "Homeless", "Temporary",
  28L, "Rental by client, with GPD TIP housing subsidy", "Homeless", "Temporary",
  19L, "Rental by client, with VASH housing subsidy", "Permanent", "Permanent",
  3L, "Permanent housing (other than RRH) for formerly homeless persons", "Permanent", "Permanent",
  31L, "Rental by client, with RRH or equivalent subsidy", "Permanent", "Permanent",
  33L, "Rental by client, with HCV voucher (tenant or project based)", "Permanent", "Permanent",
  34L, "Rental by client in a public housing unit", "Permanent", "Permanent",
  10L, "Rental by client, no ongoing housing subsidy", "Permanent", "Permanent",
  20L, "Rental by client, with other ongoing housing subsidy", "Permanent", "Permanent",
  21L, "Owned by client, with ongoing housing subsidy", "Permanent", "Permanent",
  11L, "Owned by client, no ongoing housing subsidy", "Permanent", "Permanent",
  30L, "No exit interview completed", "Not enough data", "Not enough data",
  17L, "Other", "Not enough data", "Not enough data",
  24, "Deceased", "Not enough data", "Not enough data",
  37L, "Worker unable to determine", "Not enough data", "Not enough data",
  8L, "Client doesn't know", "Not enough data", "Not enough data",
  9L, "Client refused", "Not enough data", "Not enough data",
  99L, "Data not collected", "Not enough data", "Not enough data"
)

usethis::use_data(LivingCodes, overwrite = TRUE)
