name: Deploy to shinyapps.io
on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/cohhio/ryha-ci:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate app bundle
        if: github.event_name == 'pull_request'
        run: |
          rsconnect::writeManifest(
            appDir = ".",
            appFiles = c(
              "R/",
              "inst/",
              "data/",
              "NAMESPACE",
              "DESCRIPTION",
              "app.R",
              ".Rbuildignore"
            )
          )
        shell: Rscript {0}

      - name: Configure rsconnect
        if: github.event_name != 'pull_request'
        run: |
          rsconnect::setAccountInfo(
            name = '${{ secrets.SHINYAPPS_ACCOUNT }}',
            token = '${{ secrets.SHINYAPPS_TOKEN }}',
            secret = '${{ secrets.SHINYAPPS_SECRET }}'
          )
        shell: Rscript {0}

      - name: Create .Renviron file
        if: github.event_name != 'pull_request'
        run: |
          cat << EOF > .Renviron
          APP_BACKEND=${{ secrets.APP_BACKEND }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PWD=${{ secrets.DB_PWD }}
          UPLOAD_PWD=${{ secrets.UPLOAD_PWD }}
          HASH_KEY=${{ secrets.HASH_KEY }}
          EOF

      - name: Deploy to shinyapps.io
        if: github.event_name != 'pull_request'
        run: |
          rsconnect::deployApp(
            appName = "cohhio-youth-data-dashboard",
            appTitle = "COHHIO Youth Data Dashboard",
            appFiles = c(
              # Add any additional files unique to your app here.
              "R/",
              "inst/",
              "data/",
              "NAMESPACE",
              "DESCRIPTION",
              "app.R",
              ".Renviron",
              ".Rbuildignore"
            ),
            account = "ohiobalanceofstatecoc",
            appId =  "7831250",
            lint = FALSE,
            forceUpdate = TRUE
          )
        shell: Rscript {0}
